name: WakaTime Activity

on:
  schedule:
    - cron: '0 */12 * * *' # Updates twice a day (more goated)
  workflow_dispatch:        # Allow manual trigger

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN1 }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LOC_CHART: "False"
          SHOW_TIMEZONE: "False"
